### PR TITLE
Update Docker dependency to v20.10.25

### PR DESCRIPTION
**Pull request by austinvazquez**
*Issue #, if available:*
#48 

*Description of changes:*
This change updates the docker/docker dependency to v20.10.25.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by austinvazquez** [comment]
CI failures don't make sense based on the updates here. Going to attempt to resolve those first starting with #41

**Review by BinSquare — APPROVED** [review]

**Comment by ningziwen** [comment]
@austinvazquez LGTM. Could you resolve the conflict? Do you know why dependabot can't address this update?

**Comment by BinSquare** [comment]
Let's hold-off on this, the patch is from dharma `github.com/dharmadheeraj/moby v20.10.14-0.20220615184823-6b50baca60ea+incompatible` to prevent a double calling of createLogStreams for Fargate tasks.

**Comment by ningziwen** [comment]
@BinSquare Could you point me the required change in patch? Is there an existing PR to merge it to moby? If not, I'd like to take a look to see if it is possible to merge it.

**Comment by austinvazquez** [comment]
Superseded by #107

**Pull request closed without merging**
